{
 "title": "locust",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by() (locust_requests_current_rps{name=\"Aggregated\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "sum by() (locust_requests_current_fail_per_sec{name=\"Aggregated\"})",
     "legendFormat": "fail"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "locust_requests_current_response_time_percentile_50",
     "legendFormat": "P50"
    },
    {
     "expr": "locust_requests_current_response_time_percentile_95",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Generated users",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "locust_users", "legendFormat": "users" }
   ]
  }
 ]
}