# permissions for end users to view labtemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: labtemplate-viewer-role
rules:
- apiGroups:
  - crownlabs.polito.it
  resources:
  - labtemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - crownlabs.polito.it
  resources:
  - labtemplates/status
  verbs:
  - get
