# permissions for end users to edit labtemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: labtemplate-editor-role
rules:
- apiGroups:
  - crownlabs.polito.it
  resources:
  - labtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crownlabs.polito.it
  resources:
  - labtemplates/status
  verbs:
  - get
