# permissions for end users to view memoryprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: memoryprofile-viewer-role
rules:
- apiGroups:
  - webapp.liqo.io.connectionprofile
  resources:
  - memoryprofiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.liqo.io.connectionprofile
  resources:
  - memoryprofiles/status
  verbs:
  - get
