kind: Pod
apiVersion: v1
metadata:
  name: job-profiler-pod
  namespace: profiling
spec:
  restartPolicy: Never
  containers:
    - name: job-profiler
      image: stegala/job-profiler
      env:
        - name: PROMETHEUS_URL
          value: "10.96.226.186"
        - name: PROMETHEUS_PORT
          value: "9090"
        - name: PROFILING_NAMESPACE
          value: "default" #empty means all the namespaces
        - name: BACKGROUND_ROUTINE_UPDATE_TIME
          value: "600"
        - name: BACKGROUND_ROUTINE_ENABLED
          value: "TRUE"
        - name: TIMESLOTS
          value: "4"
        - name: CPU_THRESHOLD
          value: "0.5"
        - name: MEMORY_THRESHOLD
          value: "600.0"
        - name: CPU_LOWER_THRESHOLD
          value: "0.05"
        - name: MEMORY_LOWER_THRESHOLD
          value: "50.0"