apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-profiler-deployment
  namespace: profiling
  labels:
    app: job-profiler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-profiler
  template:
    metadata:
      labels:
        app: job-profiler
    spec:
      containers:
        - name: job-profiler
          image: stegala/job-profiler
          env:
          - name: PROMETHEUS_URL
            value: "10.108.190.139"
          - name: PROMETHEUS_PORT
            value: "9090"
          - name: PROFILING_NAMESPACE
            value: "default" #empty means all the namespaces
          - name: BACKGROUND_ROUTINE_UPDATE_TIME
            value: "600"
          - name: BACKGROUND_ROUTINE_ENABLED
            value: "TRUE"
          - name: TIMESLOTS
            value: "4"
          - name: CPU_THRESHOLD
            value: ""
          - name: MEMORY_THRESHOLD
            value: ""

