kind: Pod
apiVersion: v1
metadata:
  name: job-profiler-pod
  namespace: profiling
spec:
  restartPolicy: Never
  containers:
    - name: job-profiler
      image: stegala/job-profiler
      imagePullPolicy: Always
      env:
        - name: PROMETHEUS_URL
          value: "prometheus-k8s.monitoring.svc"
        - name: PROMETHEUS_PORT
          value: "9090"
        - name: PROFILING_NAMESPACE
          value: "test-stefano" #empty means all the namespaces
        - name: BACKGROUND_ROUTINE_UPDATE_TIME
          value: "120"
        - name: BACKGROUND_ROUTINE_ENABLED
          value: "TRUE"
        - name: TIMESLOTS
          value: "1"
        - name: CPU_THRESHOLD
          value: "0.5"
        - name: MEMORY_THRESHOLD
          value: "600.0"
        - name: CPU_LOWER_THRESHOLD
          value: "0.05"
        - name: MEMORY_LOWER_THRESHOLD
          value: "50.0"
        - name: OPERATING_MODE
          value: "PROFILING_SCHEDULING" #accepted values are: PROFILING, PROFILING_SCHEDULING. PROFILING is the default