kind: Pod
apiVersion: v1
metadata:
  name: labtemplate-profiler-pod
  namespace: labtemplate-profiling
spec:
  restartPolicy: Never
  containers:
    - name: labtemplate-profiler
      image: stegala/job-profiler:crownlabs
      imagePullPolicy: Always
      env:
        - name: PROMETHEUS_URL
          value: "10.100.99.4"
        - name: PROMETHEUS_PORT
          value: "9090"
        - name: PROFILING_NAMESPACE
          value: "" #empty means all the namespaces
        - name: TIMESLOTS
          value: "4"
      resources:
        requests:
          cpu: 1000m
          memory: 64Mi
        limits:
          cpu: 1200m
          memory: 2048Mi